// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Danylo Lykov
//
// Rendering of Claude Code local-command artifacts, per doc/main.spec.md
// "Slash commands → Rendering".

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { writable, get } from 'svelte/store';
import { createParser } from './parser.js';

function freshParser() {
  const stores = {
    messages: writable([]),
    currentSessionId: writable('s1'),
    lastCost: writable(null),
    lastUsage: writable(null),
    lastContextUsage: writable(null),
  };
  const parser = createParser(stores);
  return { parser, ...stores };
}

const line = (obj) => JSON.stringify(obj);

test('local-command-caveat user message is not rendered', () => {
  const { parser, messages } = freshParser();
  parser.parseLine(line({ type: 'user', message: { role: 'user',
    content: '<local-command-caveat>Caveat: generated by the user while running local commands. DO NOT respond.</local-command-caveat>' } }));
  assert.equal(get(messages).length, 0);
});

test('command-name user message renders as the typed command', () => {
  const { parser, messages } = freshParser();
  parser.parseLine(line({ type: 'user', message: { role: 'user',
    content: '<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>' } }));
  const ms = get(messages);
  assert.equal(ms.length, 1);
  assert.equal(ms[0].role, 'user');
  assert.equal(ms[0].text, '/model opus');
  assert.equal(ms[0].isCommand, true);
});

test('local_command stdout renders as a system message', () => {
  const { parser, messages } = freshParser();
  parser.parseLine(line({ type: 'system', subtype: 'local_command',
    content: '<local-command-stdout>Set model to Opus</local-command-stdout>' }));
  const ms = get(messages);
  assert.equal(ms.length, 1);
  assert.equal(ms[0].role, 'system');
  assert.equal(ms[0].text, 'Set model to Opus');
});

test('empty local_command stdout renders nothing', () => {
  const { parser, messages } = freshParser();
  parser.parseLine(line({ type: 'system', subtype: 'local_command',
    content: '<local-command-stdout></local-command-stdout>' }));
  assert.equal(get(messages).length, 0);
});

test('compact status events render progress and outcome', () => {
  const { parser, messages } = freshParser();
  parser.parseLine(line({ type: 'system', subtype: 'status', status: 'compacting' }));
  parser.parseLine(line({ type: 'system', subtype: 'status', status: null, compact_result: 'failed', compact_error: 'Not enough messages to compact.' }));
  const texts = get(messages).map(m => m.text);
  assert.match(texts[0], /compact/i);
  assert.match(texts[1], /Not enough messages/);
});

test('result with num_turns 0 does not clobber cost/usage', () => {
  const { parser, lastCost, lastUsage } = freshParser();
  lastCost.set(1.23);
  parser.parseLine(line({ type: 'result', num_turns: 0, duration_api_ms: 0,
    total_cost_usd: 0, usage: { input_tokens: 0, output_tokens: 0 } }));
  assert.equal(get(lastCost), 1.23);
  assert.equal(get(lastUsage), null);
});

test('result from a real turn still updates cost', () => {
  const { parser, lastCost } = freshParser();
  parser.parseLine(line({ type: 'result', num_turns: 1, total_cost_usd: 0.5, usage: { input_tokens: 10 } }));
  assert.equal(get(lastCost), 0.5);
});
